language: node_js
sudo: required
services:
  - docker
branches:
  only:
    - main
cache:
  directories:
    - travis-build
before_install:
  # Clean install on any new build
  - npm run clean
jobs:
  include:
    - stage: lint jest and compile
      script:
        # clear the cache of any old build artifacts.
        - rm -rf ./travis-build
        # These can't be built in parallel because the cache is a single object and you can't add to it in parallel
        - npm run compile:prod -- --env.disableAggregateThemes --output-path $TRAVIS_BUILD_DIR/travis-build/default
    # Split out all the wdio runs to not eat up all the travis executors at once.

    - stage: wdio
      name: default-theme
      # Don't clean install
      before_install: skip
      # Rely on the cache for node_modules.. this won't work for any node modules in the packages dir but works for running wdio
      install: skip
      script:
        # using the travis env section to set env variables seems to break cache
        - CI= SITE=$TRAVIS_BUILD_DIR/travis-build/default node node_modules/.bin/wdio node_modules/terra-toolkit/config/wdio/wdio.conf.js

    - stage: deploy
      script: skip
      before_deploy:
        # Build again for deployment because we need the Public path to be updated.
        - TERRA_DEV_SITE_NEW_RELIC_LICENSE_KEY='c494ac44c8' TERRA_DEV_SITE_NEW_RELIC_APPLICATION_ID='141260567' TERRA_DEV_SITE_PUBLIC_PATH='/terra-application/' npm run compile:prod
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.com dashboard
        local_dir: $TRAVIS_BUILD_DIR/build
        on:
          branch: main
stages:
  - lint jest and compile
  - wdio
  - name: deploy
    if: type != pull_request
